name: Run Tests
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SAMTOOLS: ./scripts/ci/install-samtools.sh
      BCFTOOLS: ./scripts/ci/install-bcftools.sh
      UTILS: ./scripts/ci/install-htsget-refserver-utils.sh
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.0'
    
      - name: Install go dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
          go get github.com/mattn/goveralls

      - name: Install htsget refserver utils
        run: |
          go install github.com/ga4gh/htsget-refserver-utils@v1.0.0
          htsget-refserver-utils
    
      - name: Install samtools
        run: |
          chmod 700 ${SAMTOOLS} && source ${SAMTOOLS} && samtools --version
    
      - name: Install bcftools
        run: |
          chmod 700 ${BCFTOOLS} && source ${BCFTOOLS} && bcftools --version
    
      - name: Run tests
        run: |
          go test ./...
    
      - name: Run coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
